AWSTemplateFormatVersion: 2010-09-09

Description: This template creates an Security Groups and an EC2 instance which enables HTTP and SSH Connection.

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Enables HTTP for Web Server
        GroupName: SG-HTTP-SSH
        SecurityGroupIngress: 
          -   IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0
          -   IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIp: 0.0.0.0/0 
  MyCFInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02354e95b39ca8dec
      InstanceType: t2.micro
      KeyName: bekir-cfdemo-KeyPair
      SecurityGroups:
        - SG-HTTP-SSH
      Tags: 
        - Key: "Name"
          Value: "Web Server of StackName"